#Programmer: Logan Kelsch
#Date: 2/23/24
#COSC320 9am HOMEWORK
#Makefile for Part 3 of Homework 3

all: prog

prog: main.o
	g++ main.cpp -o prog

main.o: main.cpp
	g++ -c main.cpp

clean:
	rm -rf *o prog
